services:

# Broker Service
  broker:
    build:
      context: ./broker-service
      dockerfile: ./broker-service.dockerfile
    ports:
      - "8080:8080"
    environment:
      - AUTH_HOST=auth:50051
      - WALLET_HOST=wallet:50052
    networks:
      - myapp-network

# Authentication Service
  auth:
    depends_on:
      - auth-db
    build:
      context: ./auth-service
      dockerfile: ./auth-service.dockerfile
    ports:
      - "50051:50051"
    environment:
      JWT_KEY: MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQAwczAzq0G4TRw8Qj69FRxnuV380IQ #should be hidden in prod!!!
      DSN: "host=auth-db port=5432 user=user password=password dbname=auth_service sslmode=disable timezone=UTC connect_timeout=5"
    networks:
      - myapp-network

  auth-db:
    image: 'postgres:14.2'
    ports:
      - "5433:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_service
    volumes:
      - ./auth-service/auth-data/postgres/:/var/lib/postgresql/data/
      - ./auth-service/migrations:/migrations
    networks:
      - myapp-network
  
  # Wallet Service
  wallet:
    depends_on:
      - wallet-db
    build:
      context: ./wallet-service
      dockerfile: ./wallet-service.dockerfile
    ports:
      - "50052:50052"
    environment:
      JWT_KEY: MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQAwczAzq0G4TRw8Qj69FRxnuV380IQ #should be hidden in prod!!!
      DSN: "host=wallet-db port=5432 user=user password=password dbname=wallet_db sslmode=disable timezone=UTC connect_timeout=5"
    networks:
      - myapp-network

# Wallet Database 
  wallet-db:
    image: 'postgres:14.2'
    ports:
      - "5434:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet_db
    volumes:
      - ./wallet-service/wallet-data/postgres/:/var/lib/postgresql/data/
      - ./wallet-service/migrations:/migrations
    networks:
      - myapp-network

volumes:
  auth-data:
  wallet-data:

networks:
  myapp-network:
    driver: bridge