server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: go-log-files
    static_configs:
      - targets: ["localhost"]
        labels:
          job: auth
          # this tells Promtail “tail every .log under /logs”
          __path__: /logs/*.log
