FROM golang:1.24.0

WORKDIR /app

# Install air for hot reloading
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 50052

CMD ["air", "-c", ".air.toml"]