apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: broker:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/broker
              readOnly: true
          imagePullPolicy: Never
      volumes:
        - name: config
          configMap:
            name: broker-config
            items:
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: broker-svc
spec:
  selector:
    app: broker
  ports:
    - port: 8080
      targetPort: 8080