name: Deploy Broker Service to Local Cluster
on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'broker/**'
      - 'broker/.deployment/**'
      - 'broker/config.yaml'
  workflow_dispatch:
jobs:
  deploy-broker:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v3
      - name: Check Minikube Status
        run: |
          minikube status
      - name: Build and Import Broker Image
        run: |
          cd broker
          docker build -t broker:${{ github.sha }} .
          minikube image load broker:${{ github.sha }}
      - name: Update Deployment Image
        run: |
          sed -i '' "s|image: docker.io/library/broker:.*|image: docker.io/library/broker:${{ github.sha }}|" broker/.deployment/broker-deployment.yaml
      - name: Deploy Broker and Ingress
        run: |
          kubectl create configmap broker-config --from-file=broker/config.yaml || true
          kubectl apply -f broker/.deployment/broker-deployment.yaml
          kubectl apply -f broker/.deployment/broker-service.yaml
          kubectl apply -f broker/.deployment/ingress.yaml