name: Deploy Broker Service to Local k3d Cluster
on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'broker/**'
      - 'broker/.deployment/**'
      - 'broker/config.yaml'
  workflow_dispatch:
jobs:
  deploy-broker:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Broker Image
        run: |
          cd broker
          docker build -t kristiyankiryakov/broker:${{ github.sha }} .
          docker push kristiyankiryakov/broker:${{ github.sha }}
      - name: Deploy Broker and Ingress
        run: |
          kubectl wait --for=condition=ready pod -l app=auth --timeout=60s
          kubectl create configmap broker-config --from-file=broker/config.yaml || true
          kubectl set image -f broker/.deployment/broker-deployment.yaml broker=kristiyankiryakov/broker:${{ github.sha }}
          kubectl apply -f broker/.deployment/broker-deployment.yaml
          kubectl apply -f broker/.deployment/ingress.yaml